GET https://codeboker-customer-service.hf.space/ai-test HTTP/1.1
Content-Type: application/json

{
    "message": {
        "chat": {"id": 123},
        "text": "هاي"
    }
}
###
GET https://codeboker-customer-service.hf.space/ai-test HTTP/1.1

###
POST https://codeboker-customer-service.hf.space/webhook HTTP/1.1
Content-Type: application/json
{
    "message": {
        "chat": {"id": 123},
        "text": "السلام عليكم وؤحمة الله اريد ان استعلم عنلاالخدمات الالكترونية"
    }
}